# docker-compose --compatibility up -d

version: "3.8"

networks:
    monitoring:
        driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        volumes:
            - ./docker/prometheus/config:/etc/prometheus
            - ./docker/prometheus/data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
        ports:
            - 9090:9090
        expose:
            - 9090
        networks:
            - monitoring
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=true
        restart: unless-stopped
        ports:
            - 3000:3000
        expose:
            - 3000
        networks:
            - monitoring
